"""item.edt stat table (`Seal Online Data` container, v13).

A 92-int stat table; named columns were recovered by correlation vs the
old ItemFile v10 (item.dat). The rest stay `field_N`.
"""

from .base import Column, RecordSchema, F32, I32, register_schema

register_schema(
  "dat",
  RecordSchema(
    name="item_data",
    columns=(
      Column("id", I32),
      Column("field_1", I32),
      Column("field_2", I32),
      Column("field_3", I32),
      Column("field_4", I32),
      Column("min_fame", I32),
      Column("damage", I32),
      Column("field_7", I32),
      Column("field_8", I32),
      Column("field_9", I32),
      Column("field_10", I32),
      Column("field_11", I32),
      Column("magic_power", I32),
      Column("field_13", I32),
      Column("field_14", I32),
      Column("sta_min", I32),
      Column("field_16", I32),
      Column("defense", I32),
      Column("sta_refine_increment", F32),
      Column("field_19", I32),
      Column("field_20", I32),
      Column("field_21", I32),
      Column("field_22", I32),
      Column("attack_speed", I32),
      Column("field_24", I32),
      Column("field_25", I32),
      Column("field_26", I32),
      Column("critical_rate", I32),
      Column("field_28", I32),
      Column("evasion_rate", I32),
      Column("field_30", I32),
      Column("luck_min", I32),
      Column("movement_speed", I32),
      Column("set_id", I32),
      Column("field_34", I32),
      Column("buy_price", I32),
      Column("field_36", I32),
      Column("hp_restore", I32),
      Column("field_38", I32),
      Column("ap_restore", I32),
      Column("field_40", I32),
      Column("field_41", I32),
      Column("cooldown", I32),
      Column("field_43", I32),
      Column("field_44", I32),
      Column("field_45", I32),
      Column("field_46", I32),
      Column("field_47", I32),
      Column("field_48", I32),
      Column("field_49", I32),
      Column("field_50", I32),
      Column("field_51", I32),
      Column("luck_refine_increment", F32),
      Column("field_53", I32),
      Column("field_54", I32),
      Column("refine_ac_item_id", I32),
      Column("refine_a_item_id", I32),
      Column("refine_c_item_id", I32),
      Column("field_58", I32),
      Column("field_59", I32),
      Column("attack_range", I32),
      Column("str_min", I32),
      Column("str_refine_increment", F32),
      Column("agi_min", I32),
      Column("agi_refine_increment", F32),
      Column("int_min", I32),
      Column("int_refine_increment", F32),
      Column("field_67", I32),
      Column("field_68", I32),
      Column("wis_min", I32),
      Column("wis_refine_increment", F32),
      Column("field_71", I32),
      Column("field_72", I32),
      Column("field_73", I32),
      Column("field_74", I32),
      Column("model_id", I32),
      Column("icon_id", I32),
      Column("field_77", I32),
      Column("field_78", I32),
      Column("field_79", I32),
      Column("field_80", I32),
      Column("field_81", I32),
      Column("field_82", I32),
      Column("field_83", I32),
      Column("field_84", I32),
      Column("field_85", I32),
      Column("field_86", I32),
      Column("field_87", I32),
      Column("field_88", I32),
      Column("field_89", I32),
      Column("field_90", I32),
      Column("field_91", I32),
    ),
  ),
  patterns=(r"^item$",),
  versions=(13,),
)
